components:
  securitySchemes:
    default:
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
      type: oauth2
info:
  title: pickmeAPI
  version: v1
openapi: 3.0.1
paths:
  /pick:
    get:
      parameters: []
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
    post:
      parameters: []
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
security:
- default: []
servers:
- url: /
x-wso2-auth-header: Authorization
x-wso2-basePath: /pickmeAPI/v1
x-wso2-cors:
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
  - authorization
  - Access-Control-Allow-Origin
  - Content-Type
  - SOAPAction
  - apikey
  - Internal-Key
  accessControlAllowMethods:
  - GET
  - PUT
  - POST
  - DELETE
  - PATCH
  - OPTIONS
  accessControlAllowOrigins:
  - '*'
  corsConfigurationEnabled: false
x-wso2-production-endpoints:
  type: http
  urls:
  - https://localhost:9443/pickme
x-wso2-response-cache:
  cacheTimeoutInSeconds: 300
  enabled: false
x-wso2-sandbox-endpoints:
  type: http
  urls:
  - https://localhost:9443/pickme
x-wso2-transports:
- http
- https
