consumes:
- application/json
info:
  title: os-services
  version: Unknown
paths:
  /v2/{tenant_id}/os-services:
    get:
      description: |
        Lists running services.
      operationId: listServices
      produces:
      - application/json
      responses:
        "200":
          description: 200 response
          examples:
            application/json: |-
              {
                  "services": [
                      {
                          "status": "disabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:02.000000",
                          "host": "host1"
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:05.000000",
                          "host": "host1"
                      },
                      {
                          "status": "enabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "down",
                          "updated_at": "2012-09-19T06:55:34.000000",
                          "host": "host2"
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "down",
                          "updated_at": "2012-09-18T08:03:38.000000",
                          "host": "host2"
                      }
                  ]
              }
      summary: List services
    parameters:
    - description: |
        The ID for the tenant or account in a multi-tenancy cloud.
      in: path
      name: tenant_id
      required: true
      type: string
  /v2/{tenant_id}/os-services/detail:
    get:
      description: |
        Lists disabled services. If information exists, includes reasons why services were disabled.
      operationId: getDisableReasonDetail
      produces:
      - application/json
      responses:
        "200":
          description: 200 response
          examples:
            application/json: |-
              {
                  "services": [
                      {
                          "status": "disabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:02.000000",
                          "host": "host1",
                          "disabled_reason": "test1"
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:05.000000",
                          "host": "host1",
                          "disabled_reason": "test2"
                      },
                      {
                          "status": "enabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "down",
                          "updated_at": "2012-09-19T06:55:34.000000",
                          "host": "host2",
                          "disabled_reason": ""
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "down",
                          "updated_at": "2012-09-18T08:03:38.000000",
                          "host": "host2",
                          "disabled_reason": "test4"
                      }
                  ]
              }
      summary: List disabled services
    parameters:
    - description: |
        The ID for the tenant or account in a multi-tenancy cloud.
      in: path
      name: tenant_id
      required: true
      type: string
  /v2/{tenant_id}/os-services/disable:
    parameters:
    - description: |
        The ID for the tenant or account in a multi-tenancy cloud.
      in: path
      name: tenant_id
      required: true
      type: string
    put:
      description: |
        Disables scheduling for a service.
      operationId: disableScheduling
      produces:
      - application/json
      responses:
        "200":
          description: 200 response
          examples:
            application/json: |-
              {
                  "service": {
                      "status": "disabled",
                      "binary": "nova-compute",
                      "host": "host1"
                  }
              }
      summary: Disable scheduling for a service
  /v2/{tenant_id}/os-services/disable-log-reason:
    parameters:
    - description: |
        The ID for the tenant or account in a multi-tenancy cloud.
      in: path
      name: tenant_id
      required: true
      type: string
    put:
      description: |
        Logs information to the service table about why a service was disabled.
      operationId: disableLogReason
      produces:
      - application/json
      responses:
        "200":
          description: 200 response
          examples:
            application/json: |-
              {
                  "service": {
                      "status": "disabled",
                      "binary": "nova-compute",
                      "host": "host1",
                      "disabled_reason": "test2"
                  }
              }
      summary: Log disabled service information
  /v2/{tenant_id}/os-services/enable:
    parameters:
    - description: |
        The ID for the tenant or account in a multi-tenancy cloud.
      in: path
      name: tenant_id
      required: true
      type: string
    put:
      description: |
        Enables scheduling for a service.
      operationId: enableScheduling
      produces:
      - application/json
      responses:
        "200":
          description: 200 response
          examples:
            application/json: |-
              {
                  "service": {
                      "status": "enabled",
                      "binary": "nova-compute",
                      "host": "host1"
                  }
              }
      summary: Enable scheduling for a service
produces:
- application/json
swagger: "2.0"
